matrix:
  include:
    - language: android
      os: linux
      env: os_build=android android_target=android-16 android_abi=armeabi-v7a
    - language: java
      os: linux
      env: os_build=linux os_arch=x86
    - language: java
      os: linux
      env: os_build=linux os_arch=x86_64
    - language: java
      os: osx
      env: os_build=macosx

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - sys-img-armeabi-v7a-android-16

before_install:
  - wget https://services.gradle.org/distributions/gradle-2.12-bin.zip
  - unzip gradle-2.12-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.12
  - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - if [[ $os_build == "android" ]]; then cd android; ./travis_script.sh; fi
